// <auto-generated />
using System;
using Alexandria.Games.SuperSmashBros.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alexandria.Games.SuperSmashBros.Migrations
{
    [DbContext(typeof(SuperSmashBrosContext))]
    [Migration("20190407061109_UpdateSmashBrosMatchReport")]
    partial class UpdateSmashBrosMatchReport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("supersmashbros")
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alexandria.Games.SuperSmashBros.EF.Models.Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("Alexandria.Games.SuperSmashBros.EF.Models.FighterPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("FighterId");

                    b.Property<Guid>("MatchId");

                    b.Property<Guid>("MatchReportId");

                    b.Property<Guid>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("FighterId");

                    b.HasIndex("MatchReportId");

                    b.ToTable("FighterPicks");
                });

            modelBuilder.Entity("Alexandria.Games.SuperSmashBros.EF.Models.MatchReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("MatchSeriesId");

                    b.HasKey("Id");

                    b.ToTable("MatchReports");
                });

            modelBuilder.Entity("Alexandria.Games.SuperSmashBros.EF.Models.FighterPick", b =>
                {
                    b.HasOne("Alexandria.Games.SuperSmashBros.EF.Models.Fighter", "Fighter")
                        .WithMany("FighterPicks")
                        .HasForeignKey("FighterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alexandria.Games.SuperSmashBros.EF.Models.MatchReport", "MatchReport")
                        .WithMany("FighterPicks")
                        .HasForeignKey("MatchReportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
