version: '3.4'

services:
  alexandria:
    image: ${DOCKER_REGISTRY-}alexandria
    environment:
      - AWS_ENABLE_ENDPOINT_DISCOVERY=true
    build:
      context: .
      dockerfile: Alexandria/Dockerfile
